// build.rs — turn palettes.toml into the `Palette` enum + lookup tables.
// Output goes to OUT_DIR/palettes_generated.rs and is `include!`'d from
// `src/palette.rs`. Adding a palette is purely a TOML edit.

use serde::Deserialize;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct PaletteToml {
    name: String,
    #[serde(default)]
    aliases: Vec<String>,
    bg_top: String,
    bg_bot: String,
    glow: String,
    cool: String,
    warm: String,
    hot: String,
}

#[derive(Deserialize)]
struct Palettes {
    palette: Vec<PaletteToml>,
}

fn main() {
    println!("cargo:rerun-if-changed=palettes.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let toml_text =
        fs::read_to_string("palettes.toml").expect("reading palettes.toml at crate root");
    let parsed: Palettes = toml::from_str(&toml_text).expect("parsing palettes.toml");
    assert!(
        !parsed.palette.is_empty(),
        "palettes.toml must define at least one palette"
    );

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("palettes_generated.rs");

    let mut s = String::new();
    writeln!(
        s,
        "// Generated by build.rs from palettes.toml — do not edit."
    )
    .unwrap();
    writeln!(s).unwrap();

    // enum Palette
    writeln!(s, "#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]").unwrap();
    writeln!(s, "pub enum Palette {{").unwrap();
    for (i, p) in parsed.palette.iter().enumerate() {
        if i == 0 {
            writeln!(s, "    #[default]").unwrap();
        }
        writeln!(s, "    {},", variant(&p.name)).unwrap();
    }
    writeln!(s, "}}").unwrap();
    writeln!(s).unwrap();

    // impl Palette { ALL, input_names, colors }
    writeln!(s, "impl Palette {{").unwrap();

    writeln!(s, "    pub const ALL: &'static [Palette] = &[").unwrap();
    for p in &parsed.palette {
        writeln!(s, "        Palette::{},", variant(&p.name)).unwrap();
    }
    writeln!(s, "    ];").unwrap();
    writeln!(s).unwrap();

    writeln!(
        s,
        "    pub fn input_names(&self) -> &'static [&'static str] {{"
    )
    .unwrap();
    writeln!(s, "        match self {{").unwrap();
    for p in &parsed.palette {
        let mut names = vec![rust_str(&p.name)];
        names.extend(p.aliases.iter().map(|a| rust_str(a)));
        writeln!(
            s,
            "            Palette::{} => &[{}],",
            variant(&p.name),
            names.join(", ")
        )
        .unwrap();
    }
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "    pub(crate) fn colors(&self) -> PaletteColors {{").unwrap();
    writeln!(s, "        match self {{").unwrap();
    for p in &parsed.palette {
        writeln!(
            s,
            "            Palette::{} => PaletteColors {{",
            variant(&p.name)
        )
        .unwrap();
        emit_field(&mut s, "bg_top", &p.bg_top);
        emit_field(&mut s, "bg_bot", &p.bg_bot);
        emit_field(&mut s, "glow", &p.glow);
        emit_field(&mut s, "cool", &p.cool);
        emit_field(&mut s, "warm", &p.warm);
        emit_field(&mut s, "hot", &p.hot);
        writeln!(s, "            }},").unwrap();
    }
    writeln!(s, "        }}").unwrap();
    writeln!(s, "    }}").unwrap();
    writeln!(s, "}}").unwrap();

    fs::write(&dest, s).expect("writing palettes_generated.rs");
}

/// `"ultraviolet"` → `"Ultraviolet"` (PascalCase first letter, rest as-is).
fn variant(name: &str) -> String {
    let mut c = name.chars();
    match c.next() {
        Some(ch) => ch.to_ascii_uppercase().to_string() + c.as_str(),
        None => String::new(),
    }
}

/// Quote a string so the generated file has a valid Rust string literal.
fn rust_str(s: &str) -> String {
    format!("{:?}", s)
}

/// `:?` on f32 always includes a decimal (e.g. `10.0`), keeping the emitted
/// tuple literal unambiguously typed as float.
fn emit_field(out: &mut String, field: &str, hex: &str) {
    let [r, g, b] = parse_hex(hex);
    writeln!(out, "                {field}: ({:?}, {:?}, {:?}),", r, g, b).unwrap();
}

/// Parse `#RRGGBB` (or `RRGGBB`) into `[f32; 3]`, panicking with a clear
/// message at build time on bad input. Case-insensitive.
fn parse_hex(s: &str) -> [f32; 3] {
    let h = s.trim_start_matches('#');
    assert_eq!(
        h.len(),
        6,
        "color must be `#RRGGBB` (6 hex digits), got {s:?}"
    );
    let byte = |i: usize| {
        u8::from_str_radix(&h[i..i + 2], 16)
            .unwrap_or_else(|_| panic!("invalid hex digit in color {s:?}"))
    };
    [byte(0) as f32, byte(2) as f32, byte(4) as f32]
}
